server:
  port: 8090
#eureka:
 # instance:
 #   hostname: ${vcap.application.uris[0]:localhost}
 #   prefer-ip-address: true
  #  lease-expiration-duration-in-seconds: 20
 #   lease-renewal-interval-in-seconds: 10

   # client:
  #    service-url:
 #       defaultZone: http://localhost:8761/eureka